name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
 
    - name: Setup Clojure
      # You may pin to the exact commit or the version.
      # uses: DeLaGuardo/setup-clojure@91054c3b9dc15fdc6a2f45be47405d891e672ef0
      uses: DeLaGuardo/setup-clojure@3.1
      with:
        # The Leiningen version to make available on the path.
        lein: # optional
        # The boot-clj version to make available on the path.
        boot: # optional
        # [DEPRECATED] The tools deps version to make available on the path.
        tools-deps: # optional
        # Clojure CLI version to make availablr on the path.
        cli: # optional
