name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Clojure
      # You may pin to the exact commit or the version.
      # uses: DeLaGuardo/setup-clojure@91054c3b9dc15fdc6a2f45be47405d891e672ef0
      uses: DeLaGuardo/setup-clojure@3.1
      with:
        # [DEPRECATED] The tools deps version to make available on the path.
        tools-deps: 1.10.2
        # Clojure CLI version to make availablr on the path.
        cli: 1.10.2 ##optional

    - name: Setup GraalVM environment
      # You may pin to the exact commit or the version.
      # uses: DeLaGuardo/setup-graalvm@b990167df27a6253bcd645d6b0eed91d4c795b38
      uses: DeLaGuardo/setup-graalvm@3.1
      with:
        # The GraalVM version to make available on the path.
        graalvm-version: '21.0.0.java11'
    - name: compile
      run: cl -X:project/uberjar :main-class ggsoft.git.core :jar git.jar :sync-pom false :aot true
      
